In [1]:
import numpy as np

In [2]:
n = 500000
k = 5

In [3]:
faces = np.random.randint(0,n,(n,k))

In [4]:
faces.shape

(500000, 5)

In [5]:
num_edges_per_face = k 

In [8]:
%load_ext memory_profiler

In [19]:
%%memit
indices = np.stack(
    [np.arange(num_edges_per_face), (np.arange(num_edges_per_face) + 1) % num_edges_per_face], 
    axis=1
)

# Use advanced indexing to select face pairs
es = faces[:, indices].reshape(-1, 2)

peak memory: 148.63 MiB, increment: 0.00 MiB


In [22]:
%%memit
es = np.concatenate( [
                faces[:, [i, (i + 1) % num_edges_per_face]]
                for i in range(num_edges_per_face)
            ],
            axis=0,
        )


peak memory: 148.58 MiB, increment: 0.00 MiB


In [23]:
target_vertices = np.arange(n)

In [26]:
%%timeit
a = np.tile(target_vertices[:,None], [1,3])

1.13 ms ± 23.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [25]:
%%timeit
repeated_arr = np.repeat(target_vertices[:, np.newaxis], 3, axis=1)

1.25 ms ± 103 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [27]:
%%timeit
repeated_arr = np.stack([target_vertices]*3,axis=1)

3.12 ms ± 170 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
repeated_arr = np.stack([target_vertices]*3,axis=1)
repeated_arr.shape

(500000, 3)

In [34]:
nearest_triangles = np.random.randint(0,n, (3,3))

target_nodes = np.tile(np.arange(3)[:, None], (1, 3))
res = np.stack(
            [nearest_triangles[..., None], target_nodes[..., None]], axis=-1
        ).reshape(-1, 2)


In [35]:
nearest_triangles

array([[310133,  67769,   2770],
       [ 48884, 167275, 180288],
       [433041,  57137, 122329]])

In [36]:
target_nodes

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [37]:
res

array([[310133,      0],
       [ 67769,      0],
       [  2770,      0],
       [ 48884,      1],
       [167275,      1],
       [180288,      1],
       [433041,      2],
       [ 57137,      2],
       [122329,      2]])